export class Company{
  $key:String;
  Branch:Array<string>;
  Backlog:number;
  Batches:Array<number>;
  Breakdown:string;
  Cgpa:number;
  Ctc:number;
  Date:Date;
  Description:string;
  Location:string;
  Name:string;
  Offer:string;
  Roles:Array<string>;
  Skills:Array<string>;
  Tenth:number;
  Twelfth:number;
  Tier:string;
  ClBacklog:number;
  AppliedStudents:Array<string>;
  Rejected:Array<string>;
  InProgress:Array<string>;
  Placed:Array<string>;
  isHistory:string;
  Time:string;
  DateTime:string;
}